#pragma once
/*
 * Author: Shamil Gusseynov
*/
#define   STM32F411

void led1_on(void);
void led1_off(void);

#ifdef  STM32F411
#define LED1_PIN  		13
#define LED_GPIO_PORT 		GPIOC
#define ENABLE_LED_BUS 		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN
#define ENABLE_LED_PIN_1	GPIOC->MODER &= ~GPIO_MODER_MODER13; GPIOC->MODER |= GPIO_MODER_MODER13_0
#define LED_1_DARK		GPIOC->BSRR |= GPIO_BSRR_BS_13
#define LED_1_LIGTH		GPIOC->BSRR |= GPIO_BSRR_BR_13
#define LED1_TOGGLE		GPIOC->ODR ^= GPIO_ODR_OD13;
#endif

#ifdef  STM32F334R8T6_NUCLEO
#define LED1_PIN  		5
#define LED_GPIO_PORT 		GPIOA
#define ENABLE_LED_BUS 		RCC->AHBENR |= RCC_AHBENR_GPIOAEN
#define ENABLE_LED_PIN_1	GPIOA->MODER &= ~GPIO_MODER_MODER5; GPIOC->MODER |= GPIO_MODER_MODER5_0
#define LED_1_LIGTH		GPIOA->BSRR |= GPIO_BSRR_BS_5
#define LED_1_DARK		GPIOA->BSRR |= GPIO_BSRR_BR_5
#endif


#ifdef STM32F401CCU
#define LED1_PIN  		13
#define LED_GPIO_PORT 		GPIOC
#define ENABLE_LED_BUS 		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN
#define ENABLE_LED_PIN_1	GPIOC->MODER &= ~GPIO_MODER_MODER13; GPIOC->MODER |= GPIO_MODER_MODER13_0
#define LED_1_LIGTH		GPIOC->BSRR |= GPIO_BSRR_BR_13
#define LED_1_DARK		GPIOC->BSRR |= GPIO_BSRR_BS_13
#endif


#ifdef STM32F407VET

//both led's - red
#define LED1_PIN	 6
#define LED2_PIN	 7
#define LED_GPIO_PORT	 GPIOA
#define ENABLE_LED_BUS 		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN
#define ENABLE_LED_PIN_1	GPIOA->MODER &= ~GPIO_MODER_MODER6; GPIOA->MODER |= GPIO_MODER_MODER6_0
#define ENABLE_LED_PIN_2	GPIOA->MODER &= ~GPIO_MODER_MODER7; GPIOA->MODER |= GPIO_MODER_MODER7_0
#define LED_1_LIGTH		GPIOA->BSRR |= GPIO_BSRR_BR_6
#define LED_1_DARK		GPIOA->BSRR |= GPIO_BSRR_BS_6
#define LED_2_LIGTH		GPIOA->BSRR |= GPIO_BSRR_BR_7
#define LED_2_DARK		GPIOA->BSRR |= GPIO_BSRR_BS_7

#endif

#ifdef STM32F769NI

#define LED1_PIN	 5
#define LED2_PIN	 13
#define LED_GPIO_PORT	 GPIOJ
#define LED3_PIN	 12 // GPIOA
#define LED4_PIN	 4  // GPIOA
// set clock for port J
#define ENABLE_LED_BUS 		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOJEN
#define ENABLE_LED_PIN_1	GPIOJ->MODER &= ~GPIO_MODER_MODER5;  GPIOJ->MODER |= GPIO_MODER_MODER5_0
#define ENABLE_LED_PIN_2	GPIOJ->MODER &= ~GPIO_MODER_MODER13; GPIOJ->MODER |= GPIO_MODER_MODER13_0
#define LED_1_LIGTH		GPIOJ->BSRR |= GPIO_BSRR_BR_5
#define LED_1_DARK		GPIOJ->BSRR |= GPIO_BSRR_BS_5
#define LED_2_LIGTH		GPIOJ->BSRR |= GPIO_BSRR_BR_13
#define LED_2_DARK		GPIOJ->BSRR |= GPIO_BSRR_BS_13

#endif

#ifdef STM32F743

#define LED1_PIN	 PA1
#define LED_GPIO_PORT	 GPIOA
// set clock for port A
#define ENABLE_LED_BUS 		RCC->AHB4ENR |= RCC_AHB4ENR_GPIOAEN
#define ENABLE_LED_PIN_1	GPIOA->MODER &= ~GPIO_MODER_MODE1; GPIOA->MODER |= GPIO_MODER_MODE1_0
#define LED_1_LIGTH		GPIOA->BSRR |= GPIO_BSRR_BR1
#define LED_1_DARK		GPIOA->BSRR |= GPIO_BSRR_BS1

#endif

